name: 'Start Circle CI Release'
description: "Triggers the CircleCI pipeline"

inputs:
  # ------------------------------------------------------------------------------------
  # ENVIRONMENT SETTINGS
  SW_VERSION:
    description: "The Shopware version that should be released"
    required: true
  SET_LATEST:
    description: "Whether its the latest or not"
    required: true
  CIRCLECI_KEY:
    description: "CircleCI token"
    required: true

runs:
  using: "composite"
  steps:

    - name: Trigger CircleCI
      shell: bash
      run: |
          export CIRCLECI_KEY=$CIRCLECI_KEY
          export SW_VERSION=$SW_VERSION
          export SET_LATEST=$SET_LATEST
          cd .circleci && bash run.sh
